/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as platformAdminRouteRouteImport } from './routes/(platform)/admin/route'
import { Route as mainPathlessRouteRouteImport } from './routes/(main)/_pathless/route'
import { Route as platformAdminIndexRouteImport } from './routes/(platform)/admin/index'
import { Route as mainPathlessIndexRouteImport } from './routes/(main)/_pathless/index'
import { Route as ApiSongsCoverRouteImport } from './routes/api/songs/cover'
import { Route as ApiMoviesPosterRouteImport } from './routes/api/movies/poster'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as platformAdminSongsRouteImport } from './routes/(platform)/admin/songs'
import { Route as platformAdminSettingsRouteImport } from './routes/(platform)/admin/settings'
import { Route as platformAdminProjectsRouteImport } from './routes/(platform)/admin/projects'
import { Route as platformAdminMoviesRouteImport } from './routes/(platform)/admin/movies'
import { Route as platformAdminJobTrackerRouteImport } from './routes/(platform)/admin/job-tracker'
import { Route as platformAdminGalleryRouteImport } from './routes/(platform)/admin/gallery'
import { Route as platformAdminExperiencesRouteImport } from './routes/(platform)/admin/experiences'
import { Route as platformAdminDashboardRouteImport } from './routes/(platform)/admin/dashboard'
import { Route as platformAdminBlogsRouteImport } from './routes/(platform)/admin/blogs'
import { Route as mainPathlessBlogRouteImport } from './routes/(main)/_pathless/blog'
import { Route as mainPathlessArchivesRouteImport } from './routes/(main)/_pathless/archives'
import { Route as mainPathlessAboutRouteImport } from './routes/(main)/_pathless/about'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const platformAdminRouteRoute = platformAdminRouteRouteImport.update({
  id: '/(platform)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const mainPathlessRouteRoute = mainPathlessRouteRouteImport.update({
  id: '/(main)/_pathless',
  getParentRoute: () => rootRouteImport,
} as any)
const platformAdminIndexRoute = platformAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const mainPathlessIndexRoute = mainPathlessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)
const ApiSongsCoverRoute = ApiSongsCoverRouteImport.update({
  id: '/api/songs/cover',
  path: '/api/songs/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoviesPosterRoute = ApiMoviesPosterRouteImport.update({
  id: '/api/movies/poster',
  path: '/api/movies/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const platformAdminSongsRoute = platformAdminSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminSettingsRoute = platformAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminProjectsRoute = platformAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminMoviesRoute = platformAdminMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminJobTrackerRoute = platformAdminJobTrackerRouteImport.update({
  id: '/job-tracker',
  path: '/job-tracker',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminGalleryRoute = platformAdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminExperiencesRoute =
  platformAdminExperiencesRouteImport.update({
    id: '/experiences',
    path: '/experiences',
    getParentRoute: () => platformAdminRouteRoute,
  } as any)
const platformAdminDashboardRoute = platformAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminBlogsRoute = platformAdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const mainPathlessBlogRoute = mainPathlessBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)
const mainPathlessArchivesRoute = mainPathlessArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)
const mainPathlessAboutRoute = mainPathlessAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/not-found': typeof NotFoundRoute
  '/admin': typeof platformAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/about': typeof mainPathlessAboutRoute
  '/archives': typeof mainPathlessArchivesRoute
  '/blog': typeof mainPathlessBlogRoute
  '/admin/blogs': typeof platformAdminBlogsRoute
  '/admin/dashboard': typeof platformAdminDashboardRoute
  '/admin/experiences': typeof platformAdminExperiencesRoute
  '/admin/gallery': typeof platformAdminGalleryRoute
  '/admin/job-tracker': typeof platformAdminJobTrackerRoute
  '/admin/movies': typeof platformAdminMoviesRoute
  '/admin/projects': typeof platformAdminProjectsRoute
  '/admin/settings': typeof platformAdminSettingsRoute
  '/admin/songs': typeof platformAdminSongsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/movies/poster': typeof ApiMoviesPosterRoute
  '/api/songs/cover': typeof ApiSongsCoverRoute
  '/': typeof mainPathlessIndexRoute
  '/admin/': typeof platformAdminIndexRoute
}
export interface FileRoutesByTo {
  '/not-found': typeof NotFoundRoute
  '/login': typeof authLoginRoute
  '/about': typeof mainPathlessAboutRoute
  '/archives': typeof mainPathlessArchivesRoute
  '/blog': typeof mainPathlessBlogRoute
  '/admin/blogs': typeof platformAdminBlogsRoute
  '/admin/dashboard': typeof platformAdminDashboardRoute
  '/admin/experiences': typeof platformAdminExperiencesRoute
  '/admin/gallery': typeof platformAdminGalleryRoute
  '/admin/job-tracker': typeof platformAdminJobTrackerRoute
  '/admin/movies': typeof platformAdminMoviesRoute
  '/admin/projects': typeof platformAdminProjectsRoute
  '/admin/settings': typeof platformAdminSettingsRoute
  '/admin/songs': typeof platformAdminSongsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/movies/poster': typeof ApiMoviesPosterRoute
  '/api/songs/cover': typeof ApiSongsCoverRoute
  '/': typeof mainPathlessIndexRoute
  '/admin': typeof platformAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/not-found': typeof NotFoundRoute
  '/(main)/_pathless': typeof mainPathlessRouteRouteWithChildren
  '/(platform)/admin': typeof platformAdminRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(main)/_pathless/about': typeof mainPathlessAboutRoute
  '/(main)/_pathless/archives': typeof mainPathlessArchivesRoute
  '/(main)/_pathless/blog': typeof mainPathlessBlogRoute
  '/(platform)/admin/blogs': typeof platformAdminBlogsRoute
  '/(platform)/admin/dashboard': typeof platformAdminDashboardRoute
  '/(platform)/admin/experiences': typeof platformAdminExperiencesRoute
  '/(platform)/admin/gallery': typeof platformAdminGalleryRoute
  '/(platform)/admin/job-tracker': typeof platformAdminJobTrackerRoute
  '/(platform)/admin/movies': typeof platformAdminMoviesRoute
  '/(platform)/admin/projects': typeof platformAdminProjectsRoute
  '/(platform)/admin/settings': typeof platformAdminSettingsRoute
  '/(platform)/admin/songs': typeof platformAdminSongsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/movies/poster': typeof ApiMoviesPosterRoute
  '/api/songs/cover': typeof ApiSongsCoverRoute
  '/(main)/_pathless/': typeof mainPathlessIndexRoute
  '/(platform)/admin/': typeof platformAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/not-found'
    | '/admin'
    | '/login'
    | '/about'
    | '/archives'
    | '/blog'
    | '/admin/blogs'
    | '/admin/dashboard'
    | '/admin/experiences'
    | '/admin/gallery'
    | '/admin/job-tracker'
    | '/admin/movies'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/songs'
    | '/api/auth/$'
    | '/api/movies/poster'
    | '/api/songs/cover'
    | '/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/not-found'
    | '/login'
    | '/about'
    | '/archives'
    | '/blog'
    | '/admin/blogs'
    | '/admin/dashboard'
    | '/admin/experiences'
    | '/admin/gallery'
    | '/admin/job-tracker'
    | '/admin/movies'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/songs'
    | '/api/auth/$'
    | '/api/movies/poster'
    | '/api/songs/cover'
    | '/'
    | '/admin'
  id:
    | '__root__'
    | '/not-found'
    | '/(main)/_pathless'
    | '/(platform)/admin'
    | '/(auth)/login'
    | '/(main)/_pathless/about'
    | '/(main)/_pathless/archives'
    | '/(main)/_pathless/blog'
    | '/(platform)/admin/blogs'
    | '/(platform)/admin/dashboard'
    | '/(platform)/admin/experiences'
    | '/(platform)/admin/gallery'
    | '/(platform)/admin/job-tracker'
    | '/(platform)/admin/movies'
    | '/(platform)/admin/projects'
    | '/(platform)/admin/settings'
    | '/(platform)/admin/songs'
    | '/api/auth/$'
    | '/api/movies/poster'
    | '/api/songs/cover'
    | '/(main)/_pathless/'
    | '/(platform)/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NotFoundRoute: typeof NotFoundRoute
  mainPathlessRouteRoute: typeof mainPathlessRouteRouteWithChildren
  platformAdminRouteRoute: typeof platformAdminRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMoviesPosterRoute: typeof ApiMoviesPosterRoute
  ApiSongsCoverRoute: typeof ApiSongsCoverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(platform)/admin': {
      id: '/(platform)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof platformAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_pathless': {
      id: '/(main)/_pathless'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainPathlessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(platform)/admin/': {
      id: '/(platform)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof platformAdminIndexRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(main)/_pathless/': {
      id: '/(main)/_pathless/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainPathlessIndexRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
    '/api/songs/cover': {
      id: '/api/songs/cover'
      path: '/api/songs/cover'
      fullPath: '/api/songs/cover'
      preLoaderRoute: typeof ApiSongsCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/movies/poster': {
      id: '/api/movies/poster'
      path: '/api/movies/poster'
      fullPath: '/api/movies/poster'
      preLoaderRoute: typeof ApiMoviesPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(platform)/admin/songs': {
      id: '/(platform)/admin/songs'
      path: '/songs'
      fullPath: '/admin/songs'
      preLoaderRoute: typeof platformAdminSongsRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/settings': {
      id: '/(platform)/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof platformAdminSettingsRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/projects': {
      id: '/(platform)/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof platformAdminProjectsRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/movies': {
      id: '/(platform)/admin/movies'
      path: '/movies'
      fullPath: '/admin/movies'
      preLoaderRoute: typeof platformAdminMoviesRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/job-tracker': {
      id: '/(platform)/admin/job-tracker'
      path: '/job-tracker'
      fullPath: '/admin/job-tracker'
      preLoaderRoute: typeof platformAdminJobTrackerRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/gallery': {
      id: '/(platform)/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof platformAdminGalleryRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/experiences': {
      id: '/(platform)/admin/experiences'
      path: '/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof platformAdminExperiencesRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/dashboard': {
      id: '/(platform)/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof platformAdminDashboardRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/blogs': {
      id: '/(platform)/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof platformAdminBlogsRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(main)/_pathless/blog': {
      id: '/(main)/_pathless/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof mainPathlessBlogRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
    '/(main)/_pathless/archives': {
      id: '/(main)/_pathless/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof mainPathlessArchivesRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
    '/(main)/_pathless/about': {
      id: '/(main)/_pathless/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainPathlessAboutRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
  }
}

interface mainPathlessRouteRouteChildren {
  mainPathlessAboutRoute: typeof mainPathlessAboutRoute
  mainPathlessArchivesRoute: typeof mainPathlessArchivesRoute
  mainPathlessBlogRoute: typeof mainPathlessBlogRoute
  mainPathlessIndexRoute: typeof mainPathlessIndexRoute
}

const mainPathlessRouteRouteChildren: mainPathlessRouteRouteChildren = {
  mainPathlessAboutRoute: mainPathlessAboutRoute,
  mainPathlessArchivesRoute: mainPathlessArchivesRoute,
  mainPathlessBlogRoute: mainPathlessBlogRoute,
  mainPathlessIndexRoute: mainPathlessIndexRoute,
}

const mainPathlessRouteRouteWithChildren =
  mainPathlessRouteRoute._addFileChildren(mainPathlessRouteRouteChildren)

interface platformAdminRouteRouteChildren {
  platformAdminBlogsRoute: typeof platformAdminBlogsRoute
  platformAdminDashboardRoute: typeof platformAdminDashboardRoute
  platformAdminExperiencesRoute: typeof platformAdminExperiencesRoute
  platformAdminGalleryRoute: typeof platformAdminGalleryRoute
  platformAdminJobTrackerRoute: typeof platformAdminJobTrackerRoute
  platformAdminMoviesRoute: typeof platformAdminMoviesRoute
  platformAdminProjectsRoute: typeof platformAdminProjectsRoute
  platformAdminSettingsRoute: typeof platformAdminSettingsRoute
  platformAdminSongsRoute: typeof platformAdminSongsRoute
  platformAdminIndexRoute: typeof platformAdminIndexRoute
}

const platformAdminRouteRouteChildren: platformAdminRouteRouteChildren = {
  platformAdminBlogsRoute: platformAdminBlogsRoute,
  platformAdminDashboardRoute: platformAdminDashboardRoute,
  platformAdminExperiencesRoute: platformAdminExperiencesRoute,
  platformAdminGalleryRoute: platformAdminGalleryRoute,
  platformAdminJobTrackerRoute: platformAdminJobTrackerRoute,
  platformAdminMoviesRoute: platformAdminMoviesRoute,
  platformAdminProjectsRoute: platformAdminProjectsRoute,
  platformAdminSettingsRoute: platformAdminSettingsRoute,
  platformAdminSongsRoute: platformAdminSongsRoute,
  platformAdminIndexRoute: platformAdminIndexRoute,
}

const platformAdminRouteRouteWithChildren =
  platformAdminRouteRoute._addFileChildren(platformAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  NotFoundRoute: NotFoundRoute,
  mainPathlessRouteRoute: mainPathlessRouteRouteWithChildren,
  platformAdminRouteRoute: platformAdminRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMoviesPosterRoute: ApiMoviesPosterRoute,
  ApiSongsCoverRoute: ApiSongsCoverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
