/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as platformAdminRouteRouteImport } from './routes/(platform)/admin/route'
import { Route as mainPathlessRouteRouteImport } from './routes/(main)/_pathless/route'
import { Route as platformAdminIndexRouteImport } from './routes/(platform)/admin/index'
import { Route as mainPathlessIndexRouteImport } from './routes/(main)/_pathless/index'
import { Route as ApiSongsCoverRouteImport } from './routes/api/songs/cover'
import { Route as ApiSettingsSkillIconRouteImport } from './routes/api/settings/skill-icon'
import { Route as ApiSettingsProfileImageRouteImport } from './routes/api/settings/profile-image'
import { Route as ApiSettingsObjectRouteImport } from './routes/api/settings/object'
import { Route as ApiProjectsThumbnailRouteImport } from './routes/api/projects/thumbnail'
import { Route as ApiMoviesPosterRouteImport } from './routes/api/movies/poster'
import { Route as ApiGalleryImageRouteImport } from './routes/api/gallery/image'
import { Route as ApiExperiencesCompanyLogoRouteImport } from './routes/api/experiences/company-logo'
import { Route as ApiBlogsCoverRouteImport } from './routes/api/blogs/cover'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as platformAdminSongsRouteImport } from './routes/(platform)/admin/songs'
import { Route as platformAdminSettingsRouteImport } from './routes/(platform)/admin/settings'
import { Route as platformAdminProjectsRouteImport } from './routes/(platform)/admin/projects'
import { Route as platformAdminMoviesRouteImport } from './routes/(platform)/admin/movies'
import { Route as platformAdminJobTrackerRouteImport } from './routes/(platform)/admin/job-tracker'
import { Route as platformAdminGalleryRouteImport } from './routes/(platform)/admin/gallery'
import { Route as platformAdminExperiencesRouteImport } from './routes/(platform)/admin/experiences'
import { Route as platformAdminDashboardRouteImport } from './routes/(platform)/admin/dashboard'
import { Route as platformAdminBlogsRouteImport } from './routes/(platform)/admin/blogs'
import { Route as mainPathlessBlogRouteImport } from './routes/(main)/_pathless/blog'
import { Route as mainPathlessArchivesRouteImport } from './routes/(main)/_pathless/archives'
import { Route as mainPathlessAboutRouteImport } from './routes/(main)/_pathless/about'
import { Route as mainPathlessBlogIndexRouteImport } from './routes/(main)/_pathless/blog.index'
import { Route as platformAdminJobTrackerCreateRouteImport } from './routes/(platform)/admin/job-tracker.create'
import { Route as platformAdminBlogsCreateRouteImport } from './routes/(platform)/admin/blogs.create'
import { Route as mainPathlessBlogSlugRouteImport } from './routes/(main)/_pathless/blog.$slug'
import { Route as platformAdminJobTrackerEditIdRouteImport } from './routes/(platform)/admin/job-tracker.edit.$id'
import { Route as platformAdminBlogsEditSlugRouteImport } from './routes/(platform)/admin/blogs.edit.$slug'

const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const platformAdminRouteRoute = platformAdminRouteRouteImport.update({
  id: '/(platform)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const mainPathlessRouteRoute = mainPathlessRouteRouteImport.update({
  id: '/(main)/_pathless',
  getParentRoute: () => rootRouteImport,
} as any)
const platformAdminIndexRoute = platformAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const mainPathlessIndexRoute = mainPathlessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)
const ApiSongsCoverRoute = ApiSongsCoverRouteImport.update({
  id: '/api/songs/cover',
  path: '/api/songs/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsSkillIconRoute = ApiSettingsSkillIconRouteImport.update({
  id: '/api/settings/skill-icon',
  path: '/api/settings/skill-icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsProfileImageRoute = ApiSettingsProfileImageRouteImport.update({
  id: '/api/settings/profile-image',
  path: '/api/settings/profile-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsObjectRoute = ApiSettingsObjectRouteImport.update({
  id: '/api/settings/object',
  path: '/api/settings/object',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsThumbnailRoute = ApiProjectsThumbnailRouteImport.update({
  id: '/api/projects/thumbnail',
  path: '/api/projects/thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoviesPosterRoute = ApiMoviesPosterRouteImport.update({
  id: '/api/movies/poster',
  path: '/api/movies/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryImageRoute = ApiGalleryImageRouteImport.update({
  id: '/api/gallery/image',
  path: '/api/gallery/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExperiencesCompanyLogoRoute =
  ApiExperiencesCompanyLogoRouteImport.update({
    id: '/api/experiences/company-logo',
    path: '/api/experiences/company-logo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBlogsCoverRoute = ApiBlogsCoverRouteImport.update({
  id: '/api/blogs/cover',
  path: '/api/blogs/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const platformAdminSongsRoute = platformAdminSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminSettingsRoute = platformAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminProjectsRoute = platformAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminMoviesRoute = platformAdminMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminJobTrackerRoute = platformAdminJobTrackerRouteImport.update({
  id: '/job-tracker',
  path: '/job-tracker',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminGalleryRoute = platformAdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminExperiencesRoute =
  platformAdminExperiencesRouteImport.update({
    id: '/experiences',
    path: '/experiences',
    getParentRoute: () => platformAdminRouteRoute,
  } as any)
const platformAdminDashboardRoute = platformAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const platformAdminBlogsRoute = platformAdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => platformAdminRouteRoute,
} as any)
const mainPathlessBlogRoute = mainPathlessBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)
const mainPathlessArchivesRoute = mainPathlessArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)
const mainPathlessAboutRoute = mainPathlessAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)
const mainPathlessBlogIndexRoute = mainPathlessBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainPathlessBlogRoute,
} as any)
const platformAdminJobTrackerCreateRoute =
  platformAdminJobTrackerCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => platformAdminJobTrackerRoute,
  } as any)
const platformAdminBlogsCreateRoute =
  platformAdminBlogsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => platformAdminBlogsRoute,
  } as any)
const mainPathlessBlogSlugRoute = mainPathlessBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => mainPathlessBlogRoute,
} as any)
const platformAdminJobTrackerEditIdRoute =
  platformAdminJobTrackerEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => platformAdminJobTrackerRoute,
  } as any)
const platformAdminBlogsEditSlugRoute =
  platformAdminBlogsEditSlugRouteImport.update({
    id: '/edit/$slug',
    path: '/edit/$slug',
    getParentRoute: () => platformAdminBlogsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof platformAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/about': typeof mainPathlessAboutRoute
  '/archives': typeof mainPathlessArchivesRoute
  '/blog': typeof mainPathlessBlogRouteWithChildren
  '/admin/blogs': typeof platformAdminBlogsRouteWithChildren
  '/admin/dashboard': typeof platformAdminDashboardRoute
  '/admin/experiences': typeof platformAdminExperiencesRoute
  '/admin/gallery': typeof platformAdminGalleryRoute
  '/admin/job-tracker': typeof platformAdminJobTrackerRouteWithChildren
  '/admin/movies': typeof platformAdminMoviesRoute
  '/admin/projects': typeof platformAdminProjectsRoute
  '/admin/settings': typeof platformAdminSettingsRoute
  '/admin/songs': typeof platformAdminSongsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blogs/cover': typeof ApiBlogsCoverRoute
  '/api/experiences/company-logo': typeof ApiExperiencesCompanyLogoRoute
  '/api/gallery/image': typeof ApiGalleryImageRoute
  '/api/movies/poster': typeof ApiMoviesPosterRoute
  '/api/projects/thumbnail': typeof ApiProjectsThumbnailRoute
  '/api/settings/object': typeof ApiSettingsObjectRoute
  '/api/settings/profile-image': typeof ApiSettingsProfileImageRoute
  '/api/settings/skill-icon': typeof ApiSettingsSkillIconRoute
  '/api/songs/cover': typeof ApiSongsCoverRoute
  '/': typeof mainPathlessIndexRoute
  '/admin/': typeof platformAdminIndexRoute
  '/blog/$slug': typeof mainPathlessBlogSlugRoute
  '/admin/blogs/create': typeof platformAdminBlogsCreateRoute
  '/admin/job-tracker/create': typeof platformAdminJobTrackerCreateRoute
  '/blog/': typeof mainPathlessBlogIndexRoute
  '/admin/blogs/edit/$slug': typeof platformAdminBlogsEditSlugRoute
  '/admin/job-tracker/edit/$id': typeof platformAdminJobTrackerEditIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/about': typeof mainPathlessAboutRoute
  '/archives': typeof mainPathlessArchivesRoute
  '/admin/blogs': typeof platformAdminBlogsRouteWithChildren
  '/admin/dashboard': typeof platformAdminDashboardRoute
  '/admin/experiences': typeof platformAdminExperiencesRoute
  '/admin/gallery': typeof platformAdminGalleryRoute
  '/admin/job-tracker': typeof platformAdminJobTrackerRouteWithChildren
  '/admin/movies': typeof platformAdminMoviesRoute
  '/admin/projects': typeof platformAdminProjectsRoute
  '/admin/settings': typeof platformAdminSettingsRoute
  '/admin/songs': typeof platformAdminSongsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blogs/cover': typeof ApiBlogsCoverRoute
  '/api/experiences/company-logo': typeof ApiExperiencesCompanyLogoRoute
  '/api/gallery/image': typeof ApiGalleryImageRoute
  '/api/movies/poster': typeof ApiMoviesPosterRoute
  '/api/projects/thumbnail': typeof ApiProjectsThumbnailRoute
  '/api/settings/object': typeof ApiSettingsObjectRoute
  '/api/settings/profile-image': typeof ApiSettingsProfileImageRoute
  '/api/settings/skill-icon': typeof ApiSettingsSkillIconRoute
  '/api/songs/cover': typeof ApiSongsCoverRoute
  '/': typeof mainPathlessIndexRoute
  '/admin': typeof platformAdminIndexRoute
  '/blog/$slug': typeof mainPathlessBlogSlugRoute
  '/admin/blogs/create': typeof platformAdminBlogsCreateRoute
  '/admin/job-tracker/create': typeof platformAdminJobTrackerCreateRoute
  '/blog': typeof mainPathlessBlogIndexRoute
  '/admin/blogs/edit/$slug': typeof platformAdminBlogsEditSlugRoute
  '/admin/job-tracker/edit/$id': typeof platformAdminJobTrackerEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)/_pathless': typeof mainPathlessRouteRouteWithChildren
  '/(platform)/admin': typeof platformAdminRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(main)/_pathless/about': typeof mainPathlessAboutRoute
  '/(main)/_pathless/archives': typeof mainPathlessArchivesRoute
  '/(main)/_pathless/blog': typeof mainPathlessBlogRouteWithChildren
  '/(platform)/admin/blogs': typeof platformAdminBlogsRouteWithChildren
  '/(platform)/admin/dashboard': typeof platformAdminDashboardRoute
  '/(platform)/admin/experiences': typeof platformAdminExperiencesRoute
  '/(platform)/admin/gallery': typeof platformAdminGalleryRoute
  '/(platform)/admin/job-tracker': typeof platformAdminJobTrackerRouteWithChildren
  '/(platform)/admin/movies': typeof platformAdminMoviesRoute
  '/(platform)/admin/projects': typeof platformAdminProjectsRoute
  '/(platform)/admin/settings': typeof platformAdminSettingsRoute
  '/(platform)/admin/songs': typeof platformAdminSongsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blogs/cover': typeof ApiBlogsCoverRoute
  '/api/experiences/company-logo': typeof ApiExperiencesCompanyLogoRoute
  '/api/gallery/image': typeof ApiGalleryImageRoute
  '/api/movies/poster': typeof ApiMoviesPosterRoute
  '/api/projects/thumbnail': typeof ApiProjectsThumbnailRoute
  '/api/settings/object': typeof ApiSettingsObjectRoute
  '/api/settings/profile-image': typeof ApiSettingsProfileImageRoute
  '/api/settings/skill-icon': typeof ApiSettingsSkillIconRoute
  '/api/songs/cover': typeof ApiSongsCoverRoute
  '/(main)/_pathless/': typeof mainPathlessIndexRoute
  '/(platform)/admin/': typeof platformAdminIndexRoute
  '/(main)/_pathless/blog/$slug': typeof mainPathlessBlogSlugRoute
  '/(platform)/admin/blogs/create': typeof platformAdminBlogsCreateRoute
  '/(platform)/admin/job-tracker/create': typeof platformAdminJobTrackerCreateRoute
  '/(main)/_pathless/blog/': typeof mainPathlessBlogIndexRoute
  '/(platform)/admin/blogs/edit/$slug': typeof platformAdminBlogsEditSlugRoute
  '/(platform)/admin/job-tracker/edit/$id': typeof platformAdminJobTrackerEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/about'
    | '/archives'
    | '/blog'
    | '/admin/blogs'
    | '/admin/dashboard'
    | '/admin/experiences'
    | '/admin/gallery'
    | '/admin/job-tracker'
    | '/admin/movies'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/songs'
    | '/api/auth/$'
    | '/api/blogs/cover'
    | '/api/experiences/company-logo'
    | '/api/gallery/image'
    | '/api/movies/poster'
    | '/api/projects/thumbnail'
    | '/api/settings/object'
    | '/api/settings/profile-image'
    | '/api/settings/skill-icon'
    | '/api/songs/cover'
    | '/'
    | '/admin/'
    | '/blog/$slug'
    | '/admin/blogs/create'
    | '/admin/job-tracker/create'
    | '/blog/'
    | '/admin/blogs/edit/$slug'
    | '/admin/job-tracker/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/archives'
    | '/admin/blogs'
    | '/admin/dashboard'
    | '/admin/experiences'
    | '/admin/gallery'
    | '/admin/job-tracker'
    | '/admin/movies'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/songs'
    | '/api/auth/$'
    | '/api/blogs/cover'
    | '/api/experiences/company-logo'
    | '/api/gallery/image'
    | '/api/movies/poster'
    | '/api/projects/thumbnail'
    | '/api/settings/object'
    | '/api/settings/profile-image'
    | '/api/settings/skill-icon'
    | '/api/songs/cover'
    | '/'
    | '/admin'
    | '/blog/$slug'
    | '/admin/blogs/create'
    | '/admin/job-tracker/create'
    | '/blog'
    | '/admin/blogs/edit/$slug'
    | '/admin/job-tracker/edit/$id'
  id:
    | '__root__'
    | '/(main)/_pathless'
    | '/(platform)/admin'
    | '/(auth)/login'
    | '/(main)/_pathless/about'
    | '/(main)/_pathless/archives'
    | '/(main)/_pathless/blog'
    | '/(platform)/admin/blogs'
    | '/(platform)/admin/dashboard'
    | '/(platform)/admin/experiences'
    | '/(platform)/admin/gallery'
    | '/(platform)/admin/job-tracker'
    | '/(platform)/admin/movies'
    | '/(platform)/admin/projects'
    | '/(platform)/admin/settings'
    | '/(platform)/admin/songs'
    | '/api/auth/$'
    | '/api/blogs/cover'
    | '/api/experiences/company-logo'
    | '/api/gallery/image'
    | '/api/movies/poster'
    | '/api/projects/thumbnail'
    | '/api/settings/object'
    | '/api/settings/profile-image'
    | '/api/settings/skill-icon'
    | '/api/songs/cover'
    | '/(main)/_pathless/'
    | '/(platform)/admin/'
    | '/(main)/_pathless/blog/$slug'
    | '/(platform)/admin/blogs/create'
    | '/(platform)/admin/job-tracker/create'
    | '/(main)/_pathless/blog/'
    | '/(platform)/admin/blogs/edit/$slug'
    | '/(platform)/admin/job-tracker/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainPathlessRouteRoute: typeof mainPathlessRouteRouteWithChildren
  platformAdminRouteRoute: typeof platformAdminRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlogsCoverRoute: typeof ApiBlogsCoverRoute
  ApiExperiencesCompanyLogoRoute: typeof ApiExperiencesCompanyLogoRoute
  ApiGalleryImageRoute: typeof ApiGalleryImageRoute
  ApiMoviesPosterRoute: typeof ApiMoviesPosterRoute
  ApiProjectsThumbnailRoute: typeof ApiProjectsThumbnailRoute
  ApiSettingsObjectRoute: typeof ApiSettingsObjectRoute
  ApiSettingsProfileImageRoute: typeof ApiSettingsProfileImageRoute
  ApiSettingsSkillIconRoute: typeof ApiSettingsSkillIconRoute
  ApiSongsCoverRoute: typeof ApiSongsCoverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(platform)/admin': {
      id: '/(platform)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof platformAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_pathless': {
      id: '/(main)/_pathless'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainPathlessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(platform)/admin/': {
      id: '/(platform)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof platformAdminIndexRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(main)/_pathless/': {
      id: '/(main)/_pathless/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainPathlessIndexRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
    '/api/songs/cover': {
      id: '/api/songs/cover'
      path: '/api/songs/cover'
      fullPath: '/api/songs/cover'
      preLoaderRoute: typeof ApiSongsCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/skill-icon': {
      id: '/api/settings/skill-icon'
      path: '/api/settings/skill-icon'
      fullPath: '/api/settings/skill-icon'
      preLoaderRoute: typeof ApiSettingsSkillIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/profile-image': {
      id: '/api/settings/profile-image'
      path: '/api/settings/profile-image'
      fullPath: '/api/settings/profile-image'
      preLoaderRoute: typeof ApiSettingsProfileImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/object': {
      id: '/api/settings/object'
      path: '/api/settings/object'
      fullPath: '/api/settings/object'
      preLoaderRoute: typeof ApiSettingsObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/thumbnail': {
      id: '/api/projects/thumbnail'
      path: '/api/projects/thumbnail'
      fullPath: '/api/projects/thumbnail'
      preLoaderRoute: typeof ApiProjectsThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/movies/poster': {
      id: '/api/movies/poster'
      path: '/api/movies/poster'
      fullPath: '/api/movies/poster'
      preLoaderRoute: typeof ApiMoviesPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery/image': {
      id: '/api/gallery/image'
      path: '/api/gallery/image'
      fullPath: '/api/gallery/image'
      preLoaderRoute: typeof ApiGalleryImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/experiences/company-logo': {
      id: '/api/experiences/company-logo'
      path: '/api/experiences/company-logo'
      fullPath: '/api/experiences/company-logo'
      preLoaderRoute: typeof ApiExperiencesCompanyLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs/cover': {
      id: '/api/blogs/cover'
      path: '/api/blogs/cover'
      fullPath: '/api/blogs/cover'
      preLoaderRoute: typeof ApiBlogsCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(platform)/admin/songs': {
      id: '/(platform)/admin/songs'
      path: '/songs'
      fullPath: '/admin/songs'
      preLoaderRoute: typeof platformAdminSongsRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/settings': {
      id: '/(platform)/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof platformAdminSettingsRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/projects': {
      id: '/(platform)/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof platformAdminProjectsRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/movies': {
      id: '/(platform)/admin/movies'
      path: '/movies'
      fullPath: '/admin/movies'
      preLoaderRoute: typeof platformAdminMoviesRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/job-tracker': {
      id: '/(platform)/admin/job-tracker'
      path: '/job-tracker'
      fullPath: '/admin/job-tracker'
      preLoaderRoute: typeof platformAdminJobTrackerRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/gallery': {
      id: '/(platform)/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof platformAdminGalleryRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/experiences': {
      id: '/(platform)/admin/experiences'
      path: '/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof platformAdminExperiencesRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/dashboard': {
      id: '/(platform)/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof platformAdminDashboardRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(platform)/admin/blogs': {
      id: '/(platform)/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof platformAdminBlogsRouteImport
      parentRoute: typeof platformAdminRouteRoute
    }
    '/(main)/_pathless/blog': {
      id: '/(main)/_pathless/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof mainPathlessBlogRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
    '/(main)/_pathless/archives': {
      id: '/(main)/_pathless/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof mainPathlessArchivesRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
    '/(main)/_pathless/about': {
      id: '/(main)/_pathless/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainPathlessAboutRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
    '/(main)/_pathless/blog/': {
      id: '/(main)/_pathless/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof mainPathlessBlogIndexRouteImport
      parentRoute: typeof mainPathlessBlogRoute
    }
    '/(platform)/admin/job-tracker/create': {
      id: '/(platform)/admin/job-tracker/create'
      path: '/create'
      fullPath: '/admin/job-tracker/create'
      preLoaderRoute: typeof platformAdminJobTrackerCreateRouteImport
      parentRoute: typeof platformAdminJobTrackerRoute
    }
    '/(platform)/admin/blogs/create': {
      id: '/(platform)/admin/blogs/create'
      path: '/create'
      fullPath: '/admin/blogs/create'
      preLoaderRoute: typeof platformAdminBlogsCreateRouteImport
      parentRoute: typeof platformAdminBlogsRoute
    }
    '/(main)/_pathless/blog/$slug': {
      id: '/(main)/_pathless/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof mainPathlessBlogSlugRouteImport
      parentRoute: typeof mainPathlessBlogRoute
    }
    '/(platform)/admin/job-tracker/edit/$id': {
      id: '/(platform)/admin/job-tracker/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/job-tracker/edit/$id'
      preLoaderRoute: typeof platformAdminJobTrackerEditIdRouteImport
      parentRoute: typeof platformAdminJobTrackerRoute
    }
    '/(platform)/admin/blogs/edit/$slug': {
      id: '/(platform)/admin/blogs/edit/$slug'
      path: '/edit/$slug'
      fullPath: '/admin/blogs/edit/$slug'
      preLoaderRoute: typeof platformAdminBlogsEditSlugRouteImport
      parentRoute: typeof platformAdminBlogsRoute
    }
  }
}

interface mainPathlessBlogRouteChildren {
  mainPathlessBlogSlugRoute: typeof mainPathlessBlogSlugRoute
  mainPathlessBlogIndexRoute: typeof mainPathlessBlogIndexRoute
}

const mainPathlessBlogRouteChildren: mainPathlessBlogRouteChildren = {
  mainPathlessBlogSlugRoute: mainPathlessBlogSlugRoute,
  mainPathlessBlogIndexRoute: mainPathlessBlogIndexRoute,
}

const mainPathlessBlogRouteWithChildren =
  mainPathlessBlogRoute._addFileChildren(mainPathlessBlogRouteChildren)

interface mainPathlessRouteRouteChildren {
  mainPathlessAboutRoute: typeof mainPathlessAboutRoute
  mainPathlessArchivesRoute: typeof mainPathlessArchivesRoute
  mainPathlessBlogRoute: typeof mainPathlessBlogRouteWithChildren
  mainPathlessIndexRoute: typeof mainPathlessIndexRoute
}

const mainPathlessRouteRouteChildren: mainPathlessRouteRouteChildren = {
  mainPathlessAboutRoute: mainPathlessAboutRoute,
  mainPathlessArchivesRoute: mainPathlessArchivesRoute,
  mainPathlessBlogRoute: mainPathlessBlogRouteWithChildren,
  mainPathlessIndexRoute: mainPathlessIndexRoute,
}

const mainPathlessRouteRouteWithChildren =
  mainPathlessRouteRoute._addFileChildren(mainPathlessRouteRouteChildren)

interface platformAdminBlogsRouteChildren {
  platformAdminBlogsCreateRoute: typeof platformAdminBlogsCreateRoute
  platformAdminBlogsEditSlugRoute: typeof platformAdminBlogsEditSlugRoute
}

const platformAdminBlogsRouteChildren: platformAdminBlogsRouteChildren = {
  platformAdminBlogsCreateRoute: platformAdminBlogsCreateRoute,
  platformAdminBlogsEditSlugRoute: platformAdminBlogsEditSlugRoute,
}

const platformAdminBlogsRouteWithChildren =
  platformAdminBlogsRoute._addFileChildren(platformAdminBlogsRouteChildren)

interface platformAdminJobTrackerRouteChildren {
  platformAdminJobTrackerCreateRoute: typeof platformAdminJobTrackerCreateRoute
  platformAdminJobTrackerEditIdRoute: typeof platformAdminJobTrackerEditIdRoute
}

const platformAdminJobTrackerRouteChildren: platformAdminJobTrackerRouteChildren =
  {
    platformAdminJobTrackerCreateRoute: platformAdminJobTrackerCreateRoute,
    platformAdminJobTrackerEditIdRoute: platformAdminJobTrackerEditIdRoute,
  }

const platformAdminJobTrackerRouteWithChildren =
  platformAdminJobTrackerRoute._addFileChildren(
    platformAdminJobTrackerRouteChildren,
  )

interface platformAdminRouteRouteChildren {
  platformAdminBlogsRoute: typeof platformAdminBlogsRouteWithChildren
  platformAdminDashboardRoute: typeof platformAdminDashboardRoute
  platformAdminExperiencesRoute: typeof platformAdminExperiencesRoute
  platformAdminGalleryRoute: typeof platformAdminGalleryRoute
  platformAdminJobTrackerRoute: typeof platformAdminJobTrackerRouteWithChildren
  platformAdminMoviesRoute: typeof platformAdminMoviesRoute
  platformAdminProjectsRoute: typeof platformAdminProjectsRoute
  platformAdminSettingsRoute: typeof platformAdminSettingsRoute
  platformAdminSongsRoute: typeof platformAdminSongsRoute
  platformAdminIndexRoute: typeof platformAdminIndexRoute
}

const platformAdminRouteRouteChildren: platformAdminRouteRouteChildren = {
  platformAdminBlogsRoute: platformAdminBlogsRouteWithChildren,
  platformAdminDashboardRoute: platformAdminDashboardRoute,
  platformAdminExperiencesRoute: platformAdminExperiencesRoute,
  platformAdminGalleryRoute: platformAdminGalleryRoute,
  platformAdminJobTrackerRoute: platformAdminJobTrackerRouteWithChildren,
  platformAdminMoviesRoute: platformAdminMoviesRoute,
  platformAdminProjectsRoute: platformAdminProjectsRoute,
  platformAdminSettingsRoute: platformAdminSettingsRoute,
  platformAdminSongsRoute: platformAdminSongsRoute,
  platformAdminIndexRoute: platformAdminIndexRoute,
}

const platformAdminRouteRouteWithChildren =
  platformAdminRouteRoute._addFileChildren(platformAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  mainPathlessRouteRoute: mainPathlessRouteRouteWithChildren,
  platformAdminRouteRoute: platformAdminRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlogsCoverRoute: ApiBlogsCoverRoute,
  ApiExperiencesCompanyLogoRoute: ApiExperiencesCompanyLogoRoute,
  ApiGalleryImageRoute: ApiGalleryImageRoute,
  ApiMoviesPosterRoute: ApiMoviesPosterRoute,
  ApiProjectsThumbnailRoute: ApiProjectsThumbnailRoute,
  ApiSettingsObjectRoute: ApiSettingsObjectRoute,
  ApiSettingsProfileImageRoute: ApiSettingsProfileImageRoute,
  ApiSettingsSkillIconRoute: ApiSettingsSkillIconRoute,
  ApiSongsCoverRoute: ApiSongsCoverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
