/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainPathlessRouteRouteImport } from './routes/(main)/_pathless/route'
import { Route as mainPathlessIndexRouteImport } from './routes/(main)/_pathless/index'
import { Route as mainPathlessBlogRouteImport } from './routes/(main)/_pathless/blog'
import { Route as mainPathlessArchivesRouteImport } from './routes/(main)/_pathless/archives'
import { Route as mainPathlessAboutRouteImport } from './routes/(main)/_pathless/about'

const mainPathlessRouteRoute = mainPathlessRouteRouteImport.update({
  id: '/(main)/_pathless',
  getParentRoute: () => rootRouteImport,
} as any)
const mainPathlessIndexRoute = mainPathlessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)
const mainPathlessBlogRoute = mainPathlessBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)
const mainPathlessArchivesRoute = mainPathlessArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)
const mainPathlessAboutRoute = mainPathlessAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainPathlessRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof mainPathlessAboutRoute
  '/archives': typeof mainPathlessArchivesRoute
  '/blog': typeof mainPathlessBlogRoute
  '/': typeof mainPathlessIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof mainPathlessAboutRoute
  '/archives': typeof mainPathlessArchivesRoute
  '/blog': typeof mainPathlessBlogRoute
  '/': typeof mainPathlessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)/_pathless': typeof mainPathlessRouteRouteWithChildren
  '/(main)/_pathless/about': typeof mainPathlessAboutRoute
  '/(main)/_pathless/archives': typeof mainPathlessArchivesRoute
  '/(main)/_pathless/blog': typeof mainPathlessBlogRoute
  '/(main)/_pathless/': typeof mainPathlessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/archives' | '/blog' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/archives' | '/blog' | '/'
  id:
    | '__root__'
    | '/(main)/_pathless'
    | '/(main)/_pathless/about'
    | '/(main)/_pathless/archives'
    | '/(main)/_pathless/blog'
    | '/(main)/_pathless/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainPathlessRouteRoute: typeof mainPathlessRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)/_pathless': {
      id: '/(main)/_pathless'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainPathlessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_pathless/': {
      id: '/(main)/_pathless/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainPathlessIndexRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
    '/(main)/_pathless/blog': {
      id: '/(main)/_pathless/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof mainPathlessBlogRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
    '/(main)/_pathless/archives': {
      id: '/(main)/_pathless/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof mainPathlessArchivesRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
    '/(main)/_pathless/about': {
      id: '/(main)/_pathless/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainPathlessAboutRouteImport
      parentRoute: typeof mainPathlessRouteRoute
    }
  }
}

interface mainPathlessRouteRouteChildren {
  mainPathlessAboutRoute: typeof mainPathlessAboutRoute
  mainPathlessArchivesRoute: typeof mainPathlessArchivesRoute
  mainPathlessBlogRoute: typeof mainPathlessBlogRoute
  mainPathlessIndexRoute: typeof mainPathlessIndexRoute
}

const mainPathlessRouteRouteChildren: mainPathlessRouteRouteChildren = {
  mainPathlessAboutRoute: mainPathlessAboutRoute,
  mainPathlessArchivesRoute: mainPathlessArchivesRoute,
  mainPathlessBlogRoute: mainPathlessBlogRoute,
  mainPathlessIndexRoute: mainPathlessIndexRoute,
}

const mainPathlessRouteRouteWithChildren =
  mainPathlessRouteRoute._addFileChildren(mainPathlessRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  mainPathlessRouteRoute: mainPathlessRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
